stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - data/raw/train
    - data/raw/val
    - src/prepare.py
    outs:
    - data/prepared/test.csv
    - data/prepared/train.csv
  train:
    cmd: python src/train.py
    deps:
    - data/prepared/train.csv
    - data/raw/train
    - data/raw/val
    - src/train.py
    - src/loadData.py
    outs:
    - model/model.joblib
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - model/model.joblib
    - src/evaluate.py
    - src/loadData.py
    metrics:
    - metrics/accuracy.json:
        cache: false
